version: '3'

tasks:

  official:
    cmds:
      - go run cmd/official/main.go

  consume:
    cmds:
      - go run cmd/consume/main.go

  produce:
    cmds:
      - go run cmd/produce/main.go

  install:
    cmds:
      - go mod tidy

  lint:
    cmds:
      - go fmt ./...
      - gci write --skip-generated --skip-vendor -s standard -s default -s 'prefix(github.com/panutat-p)' -s localmodule .
