version: '3'

tasks:

  official:
    cmds:
      - go run cmd/official/main.go

  pool:
    cmds:
      - go run cmd/pool/main.go

  produce:
    cmds:
      - go run cmd/produce/main.go

  install:
    cmds:
      - go mod tidy

  lint:
    cmds:
      - gofmt -l -w .
      - gci write -s standard -s default -s 'prefix(github.com/panutat-p)' -s localmodule .
